# Kiwa SwiftLint Configuration

disabled_rules:
  - trailing_whitespace
  - line_length
  - identifier_name
  - type_body_length
  - function_body_length
  - file_length

opt_in_rules:
  - empty_count
  - closure_spacing
  - overridden_super_call
  - redundant_nil_coalescing
  - first_where
  - fatal_error_message
  - toggle_bool

excluded:
  - .build
  - Pods
  - DerivedData
  - Kiwa.xcodeproj

line_length:
  warning: 120
  error: 200
  ignores_comments: true

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 50
  error: 100

identifier_name:
  min_length: 2
  max_length: 50
  excluded:
    - id
    - x
    - y
    - i
    - j

reporter: xcode
