name: Kiwa
options:
  bundleIdPrefix: com.kiwa
  developmentLanguage: ko
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

packages:
  Defaults:
    url: https://github.com/sindresorhus/Defaults
    from: 8.0.0

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: "5.9"

targets:
  Kiwa:
    type: application
    platform: macOS
    sources:
      - path: App
      - path: Core
      - path: Models
      - path: Observables
      - path: Views
      - path: Settings
      - path: Extensions
      - path: Resources
    dependencies:
      - package: Defaults
    settings:
      base:
        PRODUCT_NAME: Kiwa
        PRODUCT_BUNDLE_IDENTIFIER: com.kiwa.app
        INFOPLIST_FILE: Info.plist
        CODE_SIGN_ENTITLEMENTS: Kiwa.entitlements
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        COMBINE_HIDPI_IMAGES: YES
        ENABLE_HARDENED_RUNTIME: YES
    info:
      path: Info.plist
      properties:
        CFBundleDisplayName: Kiwa
        LSUIElement: true
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        NSHumanReadableCopyright: "Copyright © 2026. All rights reserved."
        NSPrincipalClass: NSApplication
